[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn Mithaq.wsgi:application --bind 0.0.0.0:$PORT"


[build]
aptPackages = [
  "libglib2.0-0",
  "libgobject-2.0-0",
  "libpango-1.0-0",
  "libpangoft2-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libcairo2",
  "libharfbuzz0b",
  "libfontconfig1",
  "libffi-dev",
  "shared-mime-info",
  "fonts-noto-core",
  "fonts-noto-cjk"
]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[deploy.variables]
RAILPACK_DEPLOY_APT_PACKAGES = "libglib2.0-0 libgobject-2.0-0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libgdk-pixbuf2.0-0 libcairo2 libharfbuzz0b libfontconfig1 libffi-dev shared-mime-info fonts-noto-core fonts-noto-cjk"
