"""
Django settings for Mithaq project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")
TWILIO_PHONE_NUMBER = config("TWILIO_PHONE_NUMBER", default="")


EMAIL_BACKEND = config(
    'EMAIL_BACKEND', 
    default='django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST          = config("EMAIL_HOST",          default="smtp.gmail.com")
EMAIL_PORT          = config("EMAIL_PORT",          default=587, cast=int)
EMAIL_HOST_USER     = config("EMAIL_HOST_USER",     default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS       = config("EMAIL_USE_TLS",       default=True, cast=bool)
DEFAULT_FROM_EMAIL  = config("DEFAULT_FROM_EMAIL",  default="noreply@mithaq.com")

SITE_URL = config("SITE_URL", default="http://127.0.0.1:8000")

SECRET_KEY='django-insecure-%q19qr*sokgxyu9$&+^&!yplv9o5p7v+zn6w&%*z7i#phpt*(j'

# DEBUG=False on Railway (set DEBUG=False in Railway env vars)
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']   # Railway injects RAILWAY_PUBLIC_DOMAIN; '*' is safe behind Railway's proxy

# Add your Railway domain + any custom domain here once deployed
CSRF_TRUSTED_ORIGINS = [
    'https://mithaq-production.up.railway.app',
]
# If RAILWAY_PUBLIC_DOMAIN env var exists, trust it automatically
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_domain}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    # Local
    'core',
    'accounts',
    'audit',
    'blockchain',
    'invitations',
    'contracts',
    'dashboard',
    'milestones',
    'notifications',
    'payments',
    'signatures',
    'subscriptions',
    'wallet',
    'templates_lib',
    'verification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # (added by ghadi: for serving static files in production without needing nginx)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mithaq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates' / 'core'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Added by Remas — unread notifications count for all pages
                'notifications.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mithaq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('PGDATABASE'),
        'USER': config('PGUSER'),
        'PASSWORD': config('PGPASSWORD'),
        'HOST': config('PGHOST'),
        'PORT': config('PGPORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')   # collectstatic writes here
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core', 'static'),           # Ghadi's CSS/JS + face-api models
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # (added by ghadi: lets session-logged-in users call DRF API endpoints from browser template pages like checkout.html)
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # (added by ghadi: rate-limits the public verification API to prevent hash-enumeration abuse)
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',   # 60 requests per hour per IP for unauthenticated users
    },
}

# SimpleJWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Added by Remas — custom user model to replace Django's default auth.User
AUTH_USER_MODEL = 'accounts.User'

# (added by ghadi: Moyasar payment gateway config — Saudi-licensed, sandbox keys in .env)
# Moyasar payment gateway (Saudi-licensed)
# Note: .env uses MOYASAR_SECRET_KEY — mapped here to MOYASAR_API_KEY for internal consistency
MOYASAR_API_KEY         = config('MOYASAR_SECRET_KEY')
MOYASAR_PUBLISHABLE_KEY = config('MOYASAR_PUBLISHABLE_KEY')

MOYASAR_BASE_URL        = 'https://api.moyasar.com/v1'
MOYASAR_CALLBACK_URL    = config('MOYASAR_CALLBACK_URL', default='http://localhost:8000/api/payments/callback/')

LOGIN_URL = "accounts:sign_in"
LOGIN_REDIRECT_URL = "accounts:profile"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    },
}

